### ISSUE TITLE
自我介紹: Daniel

### ISSUE THREAD

**Issue by zarr12steven** [DevOpsTW/devopstw.club#12]
小弟只是塵世中的迷途中的專職**便當搬運工**，兼任打雜，很多還在學習中，請多多指教。

**Comment by chusiang** [comment]
請問，照片要直接用 GitHub 上的這張嗎？

**Comment by zarr12steven** [comment]
![kid_vim](https://user-images.githubusercontent.com/1249357/36381643-3b7a5f52-15c1-11e8-86cd-dcaf03f8963d.jpg)

照片用這張好了
