### ISSUE TITLE
DevOps Checklist 合併翻譯

### ISSUE THREAD

**Issue by tsengeagle** [DevOpsTW/devopstw.club#15]
[google doc的連結](https://docs.google.com/spreadsheets/d/1eP1HDb8oRyL6tidEedxy7Agr2ZYUywge3vwZDL_L6r0/edit?usp=sharing)

**Comment by theqwan-chengwei** [comment]
先轉成一般的 html 表格，之後再慢慢改網頁排版、樣式。

**Comment by tsengeagle** [comment]
已發PR #16
