### ISSUE TITLE
自我簡介：Miles - CI 行銷員

### ISSUE THREAD

**Issue by MilesChou** [DevOpsTW/devopstw.club#3]
Miles

從小熱愛電腦科技，五年前開始投入 PHP 開發，現正掉進 DevOps 坑，未來期望能讓更多人認為開發軟體是件有趣的事。

GitHub: https://github.com/MilesChou

**Comment by theqwan-chengwei** [comment]
個人大頭照呢？用 github 大頭照嗎？

**Comment by MilesChou** [comment]
Yes 使用 GitHub 大頭照

**Comment by Rukeith** [comment]
志工的自介？
