### ISSUE TITLE
自我簡介: Max

### ISSUE THREAD

**Issue by sakanamax** [DevOpsTW/devopstw.club#5]
自由軟體分享者, 喜歡社群自由無私的分享、熱愛自由軟體及 Linux 所帶來的方便性

About me:  https://sakanamax.github.io/

Blog:
https://sakananote2.blogspot.com

https://sakananote2english.blogspot.com

大頭照用 Github 這個

**Comment by chusiang** [comment]
要不冠個 **自由軟體分享者** 或 **自由軟體怖道者** 的稱號啊？

**Comment by sakanamax** [comment]
感謝, 已經加上分享者 :)
